import { Project, Skill, Experience, Testimonial, DeveloperProfile, GitHubStats } from './types';

export const developerProfile: DeveloperProfile = {
  name: "Rahul kumar",
  title: "Full-Stack Developer & Creative Technologist",
  tagline: "Building the future, one line of code at a time",
  bio: "I'm a passionate developer with expertise in creating immersive digital experiences. With a background in both engineering and design, I bridge the gap between technical excellence and creative vision. I specialize in React, Node.js, and cutting-edge web technologies.",
  avatarUrl: "/avatar.png",
  location: "Bit Ranchi",
  email: "mrrhl02@gmail.com",
  resumeUrl: "/resume.pdf",
  socialLinks: {
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    website: "https://example.com",
  },
  stats: {
    yearsExperience: 2,
    projectsCompleted: 5,
    coffeeConsumed: "50+",
  },
};

export const projects: Project[] = [
  {
    id: "1",
    title: "Neural Commerce",
    description: "AI-powered e-commerce platform with real-time recommendations",
    longDescription: "A next-generation e-commerce platform that leverages machine learning to provide personalized shopping experiences. Features include real-time product recommendations, dynamic pricing, and an AI chatbot for customer support.",
    techStack: ["Next.js", "TypeScript", "TensorFlow.js", "PostgreSQL", "Redis"],
    coverImage: { url: "/projects/neural-commerce.jpg" },
    galleryImages: [{ url: "/projects/neural-1.jpg" }, { url: "/projects/neural-2.jpg" }],
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: true,
    category: "E-Commerce",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    title: "Quantum Dashboard",
    description: "Real-time analytics dashboard with 3D data visualization",
    longDescription: "A high-performance analytics platform featuring interactive 3D charts, real-time data streaming, and customizable widgets. Built for enterprise-scale data analysis.",
    techStack: ["React", "Three.js", "D3.js", "GraphQL", "TimescaleDB"],
    coverImage: { url: "/projects/quantum-dashboard.jpg" },
    galleryImages: [{ url: "/projects/quantum-1.jpg" }, { url: "/projects/quantum-2.jpg" }],
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: true,
    category: "Data Visualization",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "3",
    title: "CyberSync",
    description: "Decentralized collaboration platform for remote teams",
    longDescription: "A secure, peer-to-peer collaboration tool that enables teams to work together in real-time without central servers. Features end-to-end encryption and offline-first architecture.",
    techStack: ["Svelte", "WebRTC", "IPFS", "Rust", "WebAssembly"],
    coverImage: { url: "/projects/cybersync.jpg" },
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: true,
    category: "Collaboration",
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "4",
    title: "HoloMeet",
    description: "WebXR virtual meeting rooms with spatial audio",
    longDescription: "An immersive virtual meeting platform that brings remote teams together in 3D spaces. Features spatial audio, avatar customization, and real-time collaboration tools.",
    techStack: ["React Three Fiber", "WebXR", "Mediasoup", "Node.js", "MongoDB"],
    coverImage: { url: "/projects/holomeet.jpg" },
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: false,
    category: "WebXR",
    createdAt: new Date("2023-11-05"),
  },
  {
    id: "5",
    title: "CodeForge",
    description: "AI-assisted code review and optimization tool",
    longDescription: "An intelligent code analysis platform that uses AI to review pull requests, suggest optimizations, and identify potential security vulnerabilities.",
    techStack: ["Python", "FastAPI", "OpenAI", "Docker", "Kubernetes"],
    coverImage: { url: "/projects/codeforge.jpg" },
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: false,
    category: "Developer Tools",
    createdAt: new Date("2023-09-18"),
  },
  {
    id: "6",
    title: "Synthwave Radio",
    description: "Web-based music streaming with audio visualizations",
    longDescription: "A retro-futuristic music streaming app featuring real-time audio visualizations, curated playlists, and a unique synthwave aesthetic.",
    techStack: ["Vue.js", "Web Audio API", "Canvas", "Supabase", "Cloudflare"],
    coverImage: { url: "/projects/synthwave.jpg" },
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: false,
    category: "Entertainment",
    createdAt: new Date("2023-07-22"),
  },
];

export const skills: Skill[] = [
  // Frontend
  { id: "1", name: "React", category: "frontend", proficiency: 95 },
  { id: "2", name: "Next.js", category: "frontend", proficiency: 92 },
  { id: "3", name: "TypeScript", category: "frontend", proficiency: 90 },
  { id: "4", name: "Three.js", category: "frontend", proficiency: 85 },
  { id: "5", name: "Tailwind CSS", category: "frontend", proficiency: 95 },
  { id: "6", name: "Vue.js", category: "frontend", proficiency: 80 },
  
  // Backend
  { id: "7", name: "Node.js", category: "backend", proficiency: 90 },
  { id: "8", name: "Python", category: "backend", proficiency: 85 },
  { id: "9", name: "PostgreSQL", category: "backend", proficiency: 88 },
  { id: "10", name: "GraphQL", category: "backend", proficiency: 82 },
  { id: "11", name: "Redis", category: "backend", proficiency: 78 },
  
  // DevOps
  { id: "12", name: "Docker", category: "devops", proficiency: 85 },
  { id: "13", name: "Kubernetes", category: "devops", proficiency: 75 },
  { id: "14", name: "AWS", category: "devops", proficiency: 80 },
  { id: "15", name: "CI/CD", category: "devops", proficiency: 88 },
  
  // Languages
  { id: "16", name: "JavaScript", category: "languages", proficiency: 95 },
  { id: "17", name: "Rust", category: "languages", proficiency: 70 },
  { id: "18", name: "Go", category: "languages", proficiency: 72 },
];

export const experiences: Experience[] = [
  {
    id: "1",
    title: "Senior Full-Stack Engineer",
    company: "TechNova Labs",
    companyUrl: "https://example.com",
    location: "San Francisco, CA",
    startDate: "2022-01",
    current: true,
    description: "Leading development of next-generation web applications with focus on 3D experiences and real-time collaboration features.",
    achievements: [
      "Architected and built a WebXR platform serving 100K+ daily users",
      "Reduced application load time by 60% through optimization",
      "Mentored team of 5 junior developers",
      "Implemented AI-powered features using GPT-4 and custom ML models",
    ],
    technologies: ["React", "Three.js", "Node.js", "PostgreSQL", "AWS"],
  },
  {
    id: "2",
    title: "Full-Stack Developer",
    company: "Digital Dynamics",
    companyUrl: "https://example.com",
    location: "Remote",
    startDate: "2019-06",
    endDate: "2021-12",
    current: false,
    description: "Developed scalable web applications and APIs for enterprise clients across fintech and healthcare sectors.",
    achievements: [
      "Built real-time trading dashboard processing 1M+ transactions daily",
      "Designed microservices architecture serving 50+ API endpoints",
      "Led migration from monolith to microservices",
    ],
    technologies: ["Vue.js", "Python", "FastAPI", "MongoDB", "Docker"],
  },
  {
    id: "3",
    title: "Frontend Developer",
    company: "Creative Studio X",
    companyUrl: "https://example.com",
    location: "Los Angeles, CA",
    startDate: "2017-03",
    endDate: "2019-05",
    current: false,
    description: "Created interactive web experiences for major brand campaigns and product launches.",
    achievements: [
      "Developed award-winning interactive campaign reaching 5M+ users",
      "Built custom animation framework used across 20+ projects",
      "Collaborated with design team to establish component library",
    ],
    technologies: ["React", "GSAP", "WebGL", "Sass", "Webpack"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    role: "VP of Engineering",
    company: "TechNova Labs",
    content: "Alex is an exceptional developer who consistently delivers beyond expectations. Their ability to combine technical expertise with creative problem-solving has been invaluable to our team.",
    avatarUrl: "/testimonials/sarah.jpg",
    rating: 5,
  },
  {
    id: "2",
    name: "Michael Torres",
    role: "Product Manager",
    company: "Digital Dynamics",
    content: "Working with Alex was a game-changer for our product. They brought innovative ideas and executed them flawlessly, always keeping the user experience at the forefront.",
    avatarUrl: "/testimonials/michael.jpg",
    rating: 5,
  },
  {
    id: "3",
    name: "Emily Zhang",
    role: "Creative Director",
    company: "Creative Studio X",
    content: "Alex has a rare combination of technical skills and creative vision. They transformed our concepts into stunning interactive experiences that exceeded client expectations.",
    avatarUrl: "/testimonials/emily.jpg",
    rating: 5,
  },
];

export const githubStats: GitHubStats = {
  totalRepos: 45,
  totalStars: 1250,
  totalForks: 320,
  topLanguages: [
    { name: "TypeScript", percentage: 45, color: "#3178c6" },
    { name: "JavaScript", percentage: 25, color: "#f7df1e" },
    { name: "Python", percentage: 15, color: "#3776ab" },
    { name: "Rust", percentage: 10, color: "#dea584" },
    { name: "Other", percentage: 5, color: "#8b8b8b" },
  ],
  contributions: 2847,
  followers: 892,
  following: 156,
};
